### ISSUE TITLE
Sometimes we get a segmentation fault when evaluating a CGP program

### ISSUE THREAD

**Issue by tupini07** [sejo95/EvolutionaryGaming#18]
This is caused by numpy C bindings, when trying to reference an "un-addressable" memory address.

We need to check why (and possibly which) function of the function set is causing this _memory explosion_. 

If needed we will need to place a limit or result size.

**Comment by hannah-seltmann** [comment]
I'm not sure it's any particular function. I played around with it a little, and sometimes it broke on very simple functions like max2. Then I had the impression that the memory explosion was caused by np.nan_to_num, so I tried running that from the python shell, which worked. The I took the genome of a program that crashed and evaluated that on the python shell, which worked too.

I think the main issue here isn't one specific function but a weird combination of things, although I don't know, what that would be.

**Comment by tupini07** [comment]
Yeah, I'm thinking that it might just be something in the structure of the function graph, where a function that makes the output larger (ie `push_back`) takes the input from another function which in turn takes input from the `push_back`. Over multiple iterations the output will grow in size. 

I'm thinking that we can just try catching the `MemoryError` exception, and returning `-inf` as the fitness for a program that explodes in this way. Or if not we could evaluate the program in a sub process and monitor the amount of memory used by said process (and kill it if necessary). 

One other idea would be to simply limit the size size of the array that a function can return

**Comment by tupini07** [comment]
We could also consider monitoring the current amount of memory used by the python process ([like this](https://stackoverflow.com/a/21632554)) and stop evaluating if we exceed a certain threshold. In my PC I've seen that the amount of memory used by the python process when evaluating is more or less 1GB. We could set a high limit (around 5GB) to make sure we leave some space for more memory intensive programs.

I tried catching the `MemoryError` exception, but this doesn't always work (in fact, it hasn't worked for me at all).

**Comment by hannah-seltmann** [comment]
I think it's best to limit the size of the arrays, not only because that's easier but also because setting a memory limit or catching the exception can lead to different results on different computers, which isn't too good for usability and reproducibility. (Although that's probably not too much of a concern for out project.)

**Comment by tupini07** [comment]
Ok I've set the maximum size for any result to a maximum of 3 million.

This is quite a lot. By looking at many CGP programs, I saw that most results have a size of around 33k, so 3 million leaves a lot of extra space, and doesn't cause any out of memory errors (at least in my PC [16 GB or RAM]). 

I'm closing issue this but we might need/want to revisit the size limit (it might be a bit too large).
