### ISSUE TITLE
Clipping in cell evaluation

### ISSUE THREAD

**Issue by hannah-seltmann** [sejo95/EvolutionaryGaming#20]
Why do we clip the values in _evaluate_ in _CGP\_cell_? It seems like we would be losing a lot of information that way.

**Comment by tupini07** [comment]
We did it for 3 reasons:

- As a way to solve #13 , where some trig functions are defined only in the domain `[-1,1]`
- So that we don't get huge numerical values
- In the _atari paper_ they also ensure that all the functions output values in the `[-1, 1]` range. 

But if you have any other ideas feel free to try them :) For instance, we could just replace all the `NaN` that we get when applying one of those trig functions with `0`. This is actually something that we already do here:

https://github.com/sejo95/EvolutionaryGaming/blob/98fd719d9e4b3a90cc4619a550dc808a8d46d0d8/CGP_cell.py#L68-L70

So we would only need to change/remove this:

https://github.com/sejo95/EvolutionaryGaming/blob/98fd719d9e4b3a90cc4619a550dc808a8d46d0d8/CGP_cell.py#L72-L73

Note that the clipping is done for all functions which are not statistical functions (again, this was copied from the atari paper). We could include the `openCV` functionset as part of these exceptions if you want.

**Comment by hannah-seltmann** [comment]
The thing is that gym gives us values from 0 to 255 if I'm not mistaken, and so we lose information that way. Could we maybe scale them, instead of clipping?
We could also consider only doing that inside of the trig functions, so that other functions could work without that restriction.

**Comment by tupini07** [comment]
The scaling idea is good but the problem is that we don't know the max and min of our "scale" :worried: When getting the input from the Atari images we know that values are between 0 and 255, but we don't know how they change after that. What I'm thinking (and this is something that we should have done before) is that we could scale the image "pixel values" from `[0, 255]` to `[-1, 1]`. 

Do you think this might be good enough? We won't be losing _initial data_ (image data) by the clipping process since this initial data is already in the correct range. 

Regarding doing the clipping only for trig functions: I think we would get many `1` and `-1` after clipping the incoming values, since these are allowed to grow in any direction.

**Comment by hannah-seltmann** [comment]
Yes, I think initial scaling makes sense.
